In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pandas.plotting import parallel_coordinates
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt

from sklearn.naive_bayes import BernoulliNB

In [20]:
file_url = r'C:\Users\Michel\git2\Ironhack-DAFT-Project7-ML-Netflix\imdb_processed_clean_encoded.csv'

In [21]:
df = pd.read_csv(file_url)

In [22]:
target='rating'

In [23]:
x=df.drop(columns=target)
#x=df_enc.drop(index=[712],columns='survived')
#x_check=titanic_enc.tail(1).drop(columns='survived')
y=round(df[target]).astype(int)

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

In [25]:
#BernoulliNB is designed for binary/boolean features (discrete data)

#probabilité d'une variable aléatoire discrète qui prend la valeur 1 avec la probabilité p 
# et la valeur  0 avec la probabilité 1 – p (q).

In [26]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)


In [27]:
### Print accuracy
acc_clf = clf.score(x_test, y_test)
print('The accuracy of the BernoulliNB is:', acc_clf * 100, '%')



The accuracy of the BernoulliNB is: 31.90830235439901 %


In [28]:
#other method for accury, with accuracy_score + PRINT
from sklearn.metrics import accuracy_score
clf.fit(x_train, y_train)
y_pred= clf.predict(x_test)
acc_score = accuracy_score(y_test, y_pred)
print(acc_score)

0.3190830235439901


In [29]:

# to see if it is overfit or underfit 
acc_clf = clf.score(x_train, y_train)
acc_clf = clf.score(x_test, y_test)


In [18]:
#print confusion matrix +PRINT
from sklearn.metrics import confusion_matrix
clf.fit(x_train, y_train)
y_pred= clf.predict(x_test)
conf_mat = confusion_matrix(y_test, y_pred) # we can add labels = ['cat1', 'cat2', 'cat3', 'cat4', 'cat5']


print(conf_mat)

[[  0   0   0   0   3   7   0   0]
 [  0   0   0   0   5  19   0   0]
 [  0   0   0   0  29  57   0   0]
 [  0   0   0   0  27 106   2   0]
 [  0   0   0   0  58 316   8   0]
 [  0   0   0   0  72 413  19   0]
 [  0   0   0   0  32 348  44   0]
 [  0   0   0   0   2  45   2   0]]
